---

services:
  web:
    container_name: "web"
    depends_on:
      - backend
    build:
      context: ./docker/web
    ports:
      - "8080:80"
  backend:
    container_name: "backend"
    build:
      context: ./docker/backend
    depends_on:
      - db
  db:
    container_name: "db"
    image: mysql:8.4
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "app"
