---

name: lint-php
on:
  pull_request:
    types: [opened, reopened, synchronize]
run-name: ${{ github.workflow }} (${{ github.ref_name }})
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  phpstan:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Composer dump autoload
        run: composer dump-autoload
      - name: Decrypt .env
        run: php artisan env:decrypt --key=${{ secrets.ENV_CI_DECRYPT_KEY }} --force --env=ci --filename=.env
      - name: Generate key
        run: php artisan key:generate
      - name: Change directory permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: PHPStan
        run: vendor/bin/phpstan analyse
  pint:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Pint
        run: vendor/bin/pint --test
